package com.xteink.companion.ui.theme

import androidx.compose.ui.graphics.Color

// Dark enough for ordinary on-primary text at AA contrast, not just large type.
internal val ExpressivePrimary = Color(0xFFB3261E)
internal val ExpressiveOnPrimary = Color(0xFFFFFFFF)
internal val ExpressivePrimaryContainer = Color(0xFFFFD2CA)
internal val ExpressiveOnPrimaryContainer = Color(0xFF3C0904)
internal val ExpressiveSecondary = Color(0xFF9A3F34)
internal val ExpressiveOnSecondary = Color(0xFFFFFFFF)
internal val ExpressiveSecondaryContainer = Color(0xFFFFE1DA)
internal val ExpressiveOnSecondaryContainer = Color(0xFF35100B)
internal val ExpressiveBackground = Color(0xFFFFF9F7)
internal val ExpressiveOnBackground = Color(0xFF211917)
internal val ExpressiveSurface = Color(0xFFFFF9F7)
internal val ExpressiveSurfaceLow = Color(0xFFFFF1ED)
internal val ExpressiveSurfaceContainer = Color(0xFFFBE8E3)
internal val ExpressiveSurfaceVariant = Color(0xFFF5DCD6)
internal val ExpressiveOutline = Color(0xFF8C716C)
internal val ExpressiveTertiary = Color(0xFF625B20)
internal val ExpressiveOnTertiary = Color(0xFFFFFFFF)
internal val ExpressiveTertiaryContainer = Color(0xFFEAE4A8)
internal val ExpressiveOnTertiaryContainer = Color(0xFF1E1C00)
internal val ExpressiveError = Color(0xFFBA1A1A)
internal val ExpressiveOnError = Color(0xFFFFFFFF)
internal val ExpressiveErrorContainer = Color(0xFFFFDAD6)
internal val ExpressiveOnErrorContainer = Color(0xFF410002)

internal val QuietPrimary = Color(0xFFF1F1F1)
internal val QuietOnPrimary = Color(0xFF111111)
internal val QuietPrimaryContainer = Color(0xFF323232)
internal val QuietOnPrimaryContainer = Color(0xFFF4F4F4)
internal val QuietSecondary = Color(0xFFD0D0D0)
internal val QuietOnSecondary = Color(0xFF191919)
internal val QuietSecondaryContainer = Color(0xFF292929)
internal val QuietOnSecondaryContainer = Color(0xFFEDEDED)
internal val QuietBackground = Color(0xFF0B0B0B)
internal val QuietOnBackground = Color(0xFFF1F1F1)
internal val QuietSurface = Color(0xFF101010)
internal val QuietSurfaceLow = Color(0xFF151515)
internal val QuietSurfaceContainer = Color(0xFF1D1D1D)
internal val QuietSurfaceVariant = Color(0xFF292929)
internal val QuietOutline = Color(0xFF777777)
internal val QuietTertiary = Color(0xFFD6D6D6)
internal val QuietOnTertiary = Color(0xFF1A1A1A)
internal val QuietTertiaryContainer = Color(0xFF3A3A3A)
internal val QuietOnTertiaryContainer = Color(0xFFF5F5F5)
internal val QuietError = Color(0xFFE8E8E8)
internal val QuietOnError = Color(0xFF141414)
internal val QuietErrorContainer = Color(0xFF4A4A4A)
internal val QuietOnErrorContainer = Color(0xFFFFFFFF)

internal val MossPrimary = Color(0xFF145C3C)
internal val MossOnPrimary = Color(0xFFFFFFFF)
internal val MossPrimaryContainer = Color(0xFFB7F2CF)
internal val MossOnPrimaryContainer = Color(0xFF00210F)
internal val CoralSecondary = Color(0xFF8D4A33)
internal val CoralOnSecondary = Color(0xFFFFFFFF)
internal val CoralSecondaryContainer = Color(0xFFFFDBCE)
internal val CoralOnSecondaryContainer = Color(0xFF351000)
internal val LightBackground = Color(0xFFFAFDF9)
internal val LightOnBackground = Color(0xFF171D19)
internal val LightSurface = Color(0xFFFAFDF9)
internal val LightSurfaceContainer = Color(0xFFEEF3EE)
internal val LightSurfaceVariant = Color(0xFFDDE5DD)
internal val LightOutline = Color(0xFF727A73)

internal val DarkPrimary = Color(0xFF9BD5B3)
internal val DarkOnPrimary = Color(0xFF00391E)
internal val DarkPrimaryContainer = Color(0xFF145C3C)
internal val DarkOnPrimaryContainer = Color(0xFFB7F2CF)
internal val DarkSecondary = Color(0xFFFFB59B)
internal val DarkOnSecondary = Color(0xFF55200F)
internal val DarkSecondaryContainer = Color(0xFF71351F)
internal val DarkOnSecondaryContainer = Color(0xFFFFDBCE)
internal val DarkBackground = Color(0xFF0F1511)
internal val DarkOnBackground = Color(0xFFDEE5DD)
internal val DarkSurface = Color(0xFF0F1511)
internal val DarkSurfaceContainer = Color(0xFF1B211D)
internal val DarkSurfaceVariant = Color(0xFF3F4942)
internal val DarkOutline = Color(0xFF89938B)
